spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/code_wiki?characterEncoding=utf8&serverTimezone=UTC
    username: codewiki
    password: '`1q2w3e4r'

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # JPA 데이터베이스 플랫폼 지정
    open-in-view: false # 웹 요청이 완료될 때 까지 동일한 'EntityManager'를 갖도록 해줌, 성능상 false
    show-sql: true # 'console'에 JPA 실행 쿼리를 출력
    hibernate:
      ddl-auto: update # 데이터베이스 초기화 전략
    properties:
      hibernate:
        format_sql: true # console 에 출력되는 쿼리를 가독성 처리
        jdbc:
          time_zone: 'Asia/Seoul' # 시간대 설정

server:
#  ssl:
#    enabled: true
#    key-store: keystore.p12
#    key-store-password: 102030
#    key-store-type: PKCS12
#    key-alias: bns-ssl
  port: 80

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # SQL 쿼리에서 ? 부분을 로그로 출력해서 확인
